#+Title: HTTP


It's an application-layer protocol for transmitting hypermedia such as HTML files etc.
It follows client-server and it's stateless which means that the server does not keep any data between two requests. 

The server sends the response while the client requests the response which is typically the data.

The requests are not directly sent to the server but go through different proxies which perform actions such as gateway's and caches.

#+begin_src 
Client <----> Proxy <----> Proxy <---> Server  
#+end_src

*Functions of Proxies*

- caching (the cache can be public or private, like the browser cache)
- filtering (like an antivirus scan or parental controls)
- load balancing (to allow multiple servers to serve different requests)
- authentication (to control access to different resources)
- logging (allowing the storage of historical information)




* _Resources_

1. [[https://developer.mozilla.org/en-US/docs/Web/HTTP][HTTP MDN DOCS]]
2. [[https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview][An overview of HTTP]]
